import { StyleSheet } from 'react-native';
import { palette, type AppTheme } from '@/theme/colors';

export const plannerStyles = (theme: AppTheme) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: theme.colors.background },
    content: { paddingHorizontal: 18, paddingTop: 4, gap: 12 },
    search: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 12,
      minHeight: 44,
      marginHorizontal: 18,
      marginBottom: 12,
    },
    input: {
      flex: 1,
      minHeight: 44,
      fontSize: 15,
      color: theme.colors.textPrimary,
      paddingVertical: 8,
    },
    segments: {
      flexDirection: 'row',
      gap: 8,
      marginHorizontal: 18,
      marginBottom: 12,
    },
    segment: {
      minWidth: 76,
      minHeight: 36,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 18,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    activeSegment: {
      backgroundColor: palette.mintStrong,
      borderColor: palette.mintStrong,
    },
    activeLabel: { color: '#fff' },
    card: {
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.border,
      borderWidth: 1,
      borderRadius: 18,
      padding: 16,
      gap: 12,
    },
    row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    grow: { flex: 1 },
    title: {
      color: theme.colors.textPrimary,
      fontSize: 17,
      lineHeight: 24,
      fontWeight: '600',
      letterSpacing: 0,
    },
    body: { color: theme.colors.textSecondary, fontSize: 14, lineHeight: 21 },
    date: { color: theme.colors.textMuted, fontSize: 12, lineHeight: 18 },
    iconButton: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 16,
    },
    empty: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 52,
      gap: 16,
    },
    modal: { flex: 1, backgroundColor: theme.colors.background },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 16,
      gap: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.textPrimary,
      flex: 1,
      textAlign: 'center',
    },
    editorTitle: {
      fontSize: 22,
      lineHeight: 30,
      fontWeight: '600',
      color: theme.colors.textPrimary,
      padding: 18,
    },
    editorBody: {
      flex: 1,
      fontSize: 16,
      lineHeight: 25,
      color: theme.colors.textPrimary,
      paddingHorizontal: 18,
      paddingTop: 12,
      textAlignVertical: 'top',
    },
    save: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 12 },
    saveText: { color: palette.mintStrong, fontSize: 16, fontWeight: '600' },
    disabled: { opacity: 0.4 },
    progressTrack: {
      height: 4,
      borderRadius: 2,
      backgroundColor: theme.colors.border,
      overflow: 'hidden',
    },
    progressFill: { height: 4, backgroundColor: palette.mint },
    goalIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: theme.colors.tabBarActiveBackground,
      justifyContent: 'center',
      alignItems: 'center',
    },
  });
