import { StyleSheet } from 'react-native';
import { type AppTheme } from '@/theme/colors';

export const plannerStyles = (theme: AppTheme) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: theme.colors.background },
    content: { paddingHorizontal: 24, paddingTop: 4, gap: 12 },
    search: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 12,
      minHeight: 44,
      marginHorizontal: 24,
      marginBottom: 12,
    },
    input: {
      flex: 1,
      minHeight: 44,
      fontSize: 15,
      color: theme.colors.textPrimary,
      paddingVertical: 8,
    },
    segments: {
      flexDirection: 'row',
      gap: 8,
      marginHorizontal: 24,
      marginBottom: 8,
    },
    segment: {
      minWidth: 76,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 22,
      paddingHorizontal: 16,
      borderWidth: 0,
      backgroundColor: 'transparent',
    },
    activeSegment: {
      backgroundColor: theme.isDark ? '#D8F3E5' : '#152D25',
    },
    activeLabel: { color: theme.isDark ? '#101916' : '#fff' },
    card: {
      backgroundColor: theme.isDark
        ? 'rgba(255,255,255,0.035)'
        : 'rgba(255,255,255,0.60)',
      borderColor: theme.isDark
        ? 'rgba(255,255,255,0.09)'
        : 'rgba(21,45,37,0.08)',
      borderWidth: 1,
      borderRadius: 18,
      padding: 16,
      gap: 10,
    },
    row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    grow: { flex: 1 },
    title: {
      color: theme.colors.textPrimary,
      fontSize: 15,
      lineHeight: 21,
      fontWeight: '600',
      letterSpacing: 0,
    },
    body: { color: theme.colors.textSecondary, fontSize: 13, lineHeight: 20 },
    date: { color: theme.colors.textSecondary, fontSize: 11, lineHeight: 16 },
    iconButton: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 16,
    },
    empty: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 28,
      gap: 12,
    },
    modal: { flex: 1, backgroundColor: theme.colors.background },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 10,
      gap: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.textPrimary,
      flex: 1,
      textAlign: 'center',
    },
    editorTitle: {
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '600',
      color: theme.colors.textPrimary,
      paddingHorizontal: 20,
      paddingVertical: 14,
      minHeight: 56,
    },
    editorBody: {
      minHeight: 112,
      maxHeight: 240,
      fontSize: 15,
      lineHeight: 24,
      color: theme.colors.textPrimary,
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 12,
      textAlignVertical: 'top',
    },
    save: {
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 16,
      borderRadius: 22,
      backgroundColor: theme.isDark ? '#D8F3E5' : '#152D25',
    },
    saveText: {
      color: theme.isDark ? '#101916' : '#FFFFFF',
      fontSize: 14,
      fontWeight: '600',
    },
    disabled: { opacity: 0.4 },
    progressTrack: {
      height: 4,
      borderRadius: 2,
      backgroundColor: theme.colors.border,
      overflow: 'hidden',
    },
    progressFill: {
      height: 4,
      backgroundColor: theme.isDark ? '#D8F3E5' : '#152D25',
    },
    goalIcon: {
      width: 36,
      height: 36,
      borderRadius: 12,
      backgroundColor: theme.isDark
        ? 'rgba(216,243,229,0.10)'
        : 'rgba(21,45,37,0.06)',
      justifyContent: 'center',
      alignItems: 'center',
    },
  });
